from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/login/', views.RoleBasedLoginView.as_view(), name='login'),
    path('accounts/register/', views.register, name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('members/', views.member_list, name='member_list'),
    path('members/add/', views.member_create, name='member_create'),
    path('members/<int:pk>/', views.member_detail, name='member_detail'),
    path('members/<int:pk>/edit/', views.member_update, name='member_update'),
    path('members/<int:pk>/delete/', views.member_delete, name='member_delete'),
    path('council-members/', views.council_member_list, name='council_member_list'),
    path('council-members/add/', views.council_member_create, name='council_member_create'),
    path('council-members/<int:pk>/', views.council_member_detail, name='council_member_detail'),
    path('council-members/<int:pk>/edit/', views.council_member_update, name='council_member_update'),
    path('council-members/<int:pk>/delete/', views.council_member_delete, name='council_member_delete'),
    path('departments/', views.department_list, name='department_list'),
    path('departments/add/', views.department_create, name='department_create'),
    path('departments/<int:pk>/', views.department_detail, name='department_detail'),
    path('departments/<int:pk>/edit/', views.department_update, name='department_update'),
    path('departments/<int:pk>/delete/', views.department_delete, name='department_delete'),
    path('choirs/', views.choir_list, name='choir_list'),
    path('choirs/add/', views.choir_create, name='choir_create'),
    path('choirs/<int:pk>/', views.choir_detail, name='choir_detail'),
    path('choirs/<int:pk>/edit/', views.choir_update, name='choir_update'),
    path('choirs/<int:pk>/delete/', views.choir_delete, name='choir_delete'),
    path('choirs/<int:choir_pk>/members/add/', views.choir_member_add, name='choir_member_add'),
    path('choir-members/<int:pk>/edit/', views.choir_member_update, name='choir_member_update'),
    path('choir-members/<int:pk>/delete/', views.choir_member_delete, name='choir_member_delete'),
    path('choirs/<int:choir_pk>/leaders/add/', views.choir_leader_add, name='choir_leader_add'),
    path('choir-leaders/<int:pk>/edit/', views.choir_leader_update, name='choir_leader_update'),
    path('choir-leaders/<int:pk>/delete/', views.choir_leader_delete, name='choir_leader_delete'),
    path('baptism/candidates/', views.candidate_list, name='candidate_list'),
    path('baptism/candidates/add/', views.candidate_create, name='candidate_create'),
    path('baptism/classes/', views.baptism_class_list, name='baptism_class_list'),
    path('baptism/classes/add/', views.baptism_class_create, name='baptism_class_create'),
    path('baptism/classes/<int:pk>/', views.baptism_class_detail, name='baptism_class_detail'),
]
