# Generated by Django 4.2.30 on 2026-06-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ELDER', 'First Church Elder'), ('SECRETARY', 'Church Secretary'), ('TREASURER', 'Church Treasurer'), ('SS_LEADER', 'Sabbath School Leader'), ('CHOIR_LEADER', 'Choir Leader'), ('DEPT_LEADER', 'Department Leader')], default='DEPT_LEADER', max_length=20),
        ),
    ]
