# Generated by Django 4.2.30 on 2026-06-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
