# Generated by Django 4.2.30 on 2026-06-04 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0007_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('choir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='asa.choir')),
            ],
        ),
        migrations.CreateModel(
            name='ChoirLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('choir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='asa.choir')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asa.member')),
            ],
        ),
        migrations.CreateModel(
            name='ChoirMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('choir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='asa.choir')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asa.member')),
            ],
            options={
                'unique_together': {('choir', 'member')},
            },
        ),
    ]
