# Generated by Django 4.2.30 on 2026-06-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0008_choir_practice_choirleader_choirmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_baptized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('CANDIDATE', 'Baptism Candidate'), ('MEMBER', 'Full Member'), ('INACTIVE', 'Inactive')], default='MEMBER', max_length=10),
        ),
        migrations.CreateModel(
            name='BaptismEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('officiant', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('candidates', models.ManyToManyField(limit_choices_to={'status': 'CANDIDATE'}, related_name='baptism_events', to='asa.member')),
            ],
        ),
        migrations.CreateModel(
            name='BaptismClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('candidates', models.ManyToManyField(limit_choices_to={'status': 'CANDIDATE'}, related_name='baptism_classes', to='asa.member')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructed_classes', to='asa.member')),
            ],
            options={
                'verbose_name_plural': 'Baptism Classes',
            },
        ),
    ]
