# Generated by Django 4.2.30 on 2026-06-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0009_member_is_baptized_member_status_baptismevent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Practice',
        ),
    ]
