# Generated by Django 4.2.30 on 2026-06-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0010_delete_practice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaptismEvent',
        ),
    ]
